### ISSUE TITLE
No valid DOI for dataset

### ISSUE THREAD

**Issue by stefanbringuier** [KRICT-DATA/SIMD#1]
The current DOI on the [README](README.md/#a-public-database-of-thermoelectric-materials-and-system-identified-material-representation-for-data-driven-discovery) is given as:

[https://doi.org/10.xxxx/xxxxxxxxx](https://doi.org/10.xxxx/xxxxxxxxx)

Is there a valid DOI for this dataset? I don't see anything on the corresponding paper: https://doi.org/10.1038/s41524-022-00897-2

**Comment by KRICT-DATA** [comment]
DOI of this paper is https://doi.org/10.1038/s41524-022-00897-2, and I updated the DOI of the paper.
The dataset of the paper is in the dataset folder of this GitHub repository.
However, the source dataset for the SIMD-based transfer learning is not publicly available due to the license of the source dataset.

**Comment by stefanbringuier** [comment]
Thanks for the info.
